version: "3"
networks:
  net:
    driver: overlay
services:
  service-socket:
    image: sticky-socket:latest
    networks:
      - net
    ports:
      - "3000"
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 3  
      labels:
        - "traefik.docker.network=sticky_net"
        - "traefik.port=3000"
        - "traefik.sticky.frontend.rule=PathPrefix:/sticky;"
        - "traefik.socket.frontend.rule=PathPrefix:/socket.io;"
        - "traefik.backend.loadbalancer.stickiness=true"
  nginx:
    image: nginx-proxy:latest
    networks:
      - net
    ports:
      - "8000:80"
    deploy:      
      placement:
         constraints: [node.role == manager]

  loadbalancer:
    image: traefik:v1.7
    command: 
      - --docker
      - --docker.swarmmode
      - --api
    ports:
      - 8001:80
      - 9090:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
         constraints: [node.role == manager]
    networks:
      - net